# Generated by Django 3.2.9 on 2022-02-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stopwatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minu', models.IntegerField()),
                ('sec', models.IntegerField()),
                ('mil', models.IntegerField()),
            ],
        ),
    ]
