# Generated by Django 3.2.9 on 2022-02-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopwatch',
            name='mil',
        ),
        migrations.RemoveField(
            model_name='stopwatch',
            name='minu',
        ),
        migrations.RemoveField(
            model_name='stopwatch',
            name='sec',
        ),
        migrations.AlterField(
            model_name='stopwatch',
            name='hour',
            field=models.CharField(max_length=64),
        ),
    ]
